export const
Shop = r => require(['@/pages/detail/Index.vue'], r),
DetailShop = r => require(['@/pages/detail/shop/Index.vue'], r),
Message = r => require(['@/pages/detail/message/Index.vue'], r),
Chat = r => require(['@/pages/detail/chat/Index.vue'], r),
Order = r => require(['@/pages/detail/order/Index.vue'], r),
Friends = r => require(['@/pages/detail/friends/Index.vue'], r),
Dynamic = r => require(['@/pages/detail/dynamic/Index.vue'], r),
Passers = r => require(['@/pages/detail/passers/Index.vue'], r),
OrderWay = r => require(['@/pages/detail/orderWay/Index.vue'], r),
Collection = r => require(['@/pages/detail/collection/Index.vue'], r),
Version = r => require(['@/pages/detail/version/Index.vue'], r),
Injection = r => require(['@/pages/detail/injection/Index.vue'], r),
SetUp = r => require(['@/pages/detail/set-up/Index.vue'], r),
Certification = r => require(['@/pages/detail/certification/Index.vue'], r),
PersonalInfo = r => require(['@/pages/detail/personalInfo/Index.vue'], r)